---
apiVersion: v1
kind: Secret
metadata:
  name: mgharnish91-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-deploy/mgharnish91-gateway-gitops
